services:
  frontend:
    build:
      context: .
      dockerfile: ./build/package/prod/frontend.prod.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    depends_on:
      - surrealdb
      - redis
      - tinyllama
    build:
      context: .
      dockerfile: ./build/package/prod/backend.prod.dockerfile
    volumes:
      - ./:/app
    ports:
      - "8090:8090"
    environment:
      - GO_ENV=production
    networks:
      - app-network

  tinyllama:
    build:
      context: .
      dockerfile: ./build/package/tinyllama.dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=6m
      - OLLAMA_MAX_LOADED_MODELS=1
    networks:
      - app-network

  surrealdb:
    build:
      context: .
      dockerfile: ./build/package/surrealdb.dockerfile
    command: start --user root --pass root
    ports:
      - "8000:8000"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    networks:
      - app-network

  redis:
    build:
      context: .
      dockerfile: ./build/package/redis.dockerfile
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
