services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: ./build/package/dev.frontend.dockerfile
    volumes:
      - ./web:/app # Mount app to allow for hot-reloading
      - /app/node_modules  # Don't overwrite node_modules
    ports:
      - "3000:3000"  # Expose Next.js app on port 3000
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  # Backend service
  backend:
    depends_on:
      - surrealdb
      - redis
      - tinyllama
    build:
      context: .
      dockerfile: ./build/package/dev.backend.dockerfile
    volumes:
      - ./:/app
    ports:
      - "8090:8090"
    environment:
      - GO_ENV=development
    networks:
      - app-network

  # TinyLlama service (LLM container)
  tinyllama:
    build:
      context: .
      dockerfile: ./build/package/dev.tinyllama.dockerfile
    ports:
      - "11434:11434"
    networks:
      - app-network

  # Database service
  surrealdb:
    build:
      context: .
      dockerfile: ./build/package/dev.surrealdb.dockerfile
    command: start --user root --pass root
    ports:
      - "8000:8000"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    networks:
      - app-network

  # Cache service
  redis:
    build:
      context: .
      dockerfile: ./build/package/dev.redis.dockerfile
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
    networks:
      - app-network

# Define the custom network
networks:
  app-network:
    driver: bridge
