name: Formatter CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-and-fix-formatting:
    name: Check and Fix Code Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---- TypeScript, JavaScript, CSS, SCSS, Markdown (Prettier) ----
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Prettier
        run: npm install -g prettier

      - name: Fix formatting for TypeScript, JavaScript, CSS, SCSS, and Markdown with Prettier
        id: prettier-fix
        run: prettier --write "**/*.{ts,tsx,mjs,md,css,scss}"

      - name: Check for changes after Prettier
        run: git status --porcelain
        id: check_prettier_changes

      # ---- Golang (gofmt) ----
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Fix formatting for Go files with gofmt
        id: gofmt-fix
        run: find . -name '*.go' -exec gofmt -w {} +

      - name: Check for changes after gofmt
        run: git status --porcelain
        id: check_gofmt_changes

      # ---- Commit and push the changes (if any) ----
      - name: Commit and push changes (if any)
        if: steps.check_prettier_changes.outputs.changes || steps.check_gofmt_changes.outputs.changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "fix: apply code formatting fixes"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
